### ISSUE TITLE
Dynamic Model Improvement for 2nd Iteration

### ISSUE THREAD

**Issue by aliblt** [abulut96/2E.Planet-Trip#5]
This part needs improvement. Lets talk about it here before the second iteration.

https://docs.google.com/document/d/13GlavwkCAwFnmgoArCE0JigSItNKrR5gYmo_yQcnLtg/edit#heading=h.i2wh0ypnp1fm

**Comment by SerdarAtalay** [comment]
This is a great issue to talk about, alongside with the organization of our report (too many nested sub-topics, also needs to be named better than section #.#.1, #.#.2 ... and so on. Diagrams can be changed in a way to express ideas in my humble opinion).

Maybe we need a professional feedback on the dynamic modeling, so I'm assigning our teaching assistant for his expertise.

Object class has to be modified as well, we should discuss about it on our next meeting tomorrow.

Thanks for notifying.
